-- -- local url = 'https://raw.githubusercontent.com/MyNameIsTrez/ComputerCraft-Data-Storage/master/'
-- local url = 'https://github.com/MyNameIsTrez/ComputerCraft-Data-Storage/blob/master'
-- local str = https.get(url)
-- local handle = io.open('test.html', 'w')
-- handle:write(str)
-- handle:close()