print("|.       .      .")
print("|^/~\\        ,   ")
print("I lI|^+-R---R-R--")
print("|.\\_/^|,    ,    ")
print("I                ")
print("| .      .       ")
print("|    .         . ")
print("+-I--^/~\\        ")
print("   .  lK|  ,     ")
print("      \\_/        ")
print("  .   > ,    )--K")
print("      -K-K-K-)-K-")
